language: php

sudo: false

# whitelist for building branches
branches:
  only:
  - v3

matrix:
  include:
  - php: 5.6
  - php: 7
  - php: 7.1
  - php: 7.2
  fast_finish: true

before_install:
- composer self-update

before_script:
- composer install

script:
- vendor/bin/phpunit --configuration phpunit.xml

after_success:
- travis_retry php vendor/bin/php-coveralls